//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceClaims
    {
        public int claimID { get; set; }
        public int userID { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string description { get; set; }
        public string claimType { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
