//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceClaims
    {
        public int claimID { get; set; }
        public int employeeID { get; set; }
        public int managerID { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string description { get; set; }
        public string claimType { get; set; }
        public bool isApproved { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Managers Managers { get; set; }
    }
}
