//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int contactID { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users User { get; set; }
    }
}
