//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.AbsenceClaims = new HashSet<AbsenceClaims>();
            this.Availibility1 = new HashSet<Availibility>();
            this.Shifts = new HashSet<Shifts>();
            this.Managers1 = new HashSet<Managers>();
        }
    
        public int employeeID { get; set; }
        public int userID { get; set; }
        public int availibilityID { get; set; }
        public int managerID { get; set; }
        public System.DateTime hireDate { get; set; }
        public System.DateTime fireDate { get; set; }
        public string position { get; set; }
        public string section { get; set; }
        public string employmentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenceClaims> AbsenceClaims { get; set; }
        public virtual Availibility Availibility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Availibility> Availibility1 { get; set; }
        public virtual Managers Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shifts> Shifts { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Managers> Managers1 { get; set; }
    }
}
