//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JanusModelContainer : DbContext
    {
        public JanusModelContainer()
            : base("name=JanusModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Availibility> Availibilities { get; set; }
        public virtual DbSet<Shifts> Shifts { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<AbsenceClaims> AbsenceClaims { get; set; }
        public virtual DbSet<shiftRequests> shiftRequests { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Recovery> Recoveries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
    }
}
