//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int managerID { get; set; }
        public string employeeID { get; set; }
        public string isAdmin { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employees Employee { get; set; }
    }
}
