//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recovery
    {
        public int recoveryID { get; set; }
        public int userID { get; set; }
        public int questionID { get; set; }
        public string userAnswer { get; set; }
    
        public virtual Users User { get; set; }
        public virtual Questions Question { get; set; }
    }
}
