//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janus
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiftRequests
    {
        public int shiftRequestID { get; set; }
        public string managerSignOff { get; set; }
        public string requestor { get; set; }
        public int requestorID { get; set; }
        public int requestorShiftID { get; set; }
        public string requestorShift { get; set; }
        public string requestWith { get; set; }
        public int requestWithShiftID { get; set; }
        public string requestWithShift { get; set; }
        public int requestWithID { get; set; }
        public Nullable<bool> requestConfirmed { get; set; }
        public string requestStatus { get; set; }
    }
}
